export const menu = [
  {
    id: 1,
    title: "main",
    listItems: [
      {
        id: 1,
        title: "Homepage",
        url: "/",
        icon: "home.svg",
      },
      {
        id: 2,
        title: "Profile",
        url: "/users/1",
        icon: "user.svg",
      },
      {
        id: 2,
        title: "Training and Resources",
        url: "/users/1",
        icon: "re.svg",
      },
    ],
  },
  {
    id: 2,
    title: "General",
    listItems: [
      {
        id: 1,
        title: "Other Atheletes",
        url: "/users",
        icon: "ath.svg",
      },
      {
        id: 2,
        title: "Confidential Chats",
        url: "/products",
        icon: "chats.svg",
      },
      {
        id: 3,
        title: "WhistleBlower",
        url: "/orders",
        icon: "whistle.svg",
      },
      {
        id: 4,
        title: "Social Media Monitoring ",
        url: "/posts",
        icon: "social media.svg",
      },
    ],
  },
  {
    id: 3,
    title: "Detectors",
    listItems: [
      {
        id: 1,
        title: "AI Doping Detector",
        url: "/",
        icon: "detector.svg",
      },
      {
        id: 2,
        title: "Weight Incrementor Detector",
        url: "/",
        icon: "weight.svg",
      },
      {
        id: 3,
        title: "Performance Spike Detector",
        url: "/",
        icon: "performance.svg",
      },
      {
        id: 4,
        title: "Steroid Metabolite Detector",
        url: "/",
        icon: "steroid.svg",
      },
    ],
  },
  {
    id: 4,
    title: "Medical Records",
    listItems: [
      {
        id: 1,
        title: "Athlete Biological Passport",
        url: "/",
        icon: "setting.svg",
      },
      {
        id: 2,
        title: "Urinalysis Reports",
        url: "/",
        icon: "backup.svg",
      },
      {
        id: 2,
        title: "Cardiovascular Health Reports",
        url: "/",
        icon: "backup.svg",
      },
      {
        id: 2,
        title: "Endocrine Profile Reports",
        url: "/",
        icon: "backup.svg",
      },
    ],
  },
  {
    id: 5,
    title: "analytics",
    listItems: [
      {
        id: 1,
        title: "GeoSpatial Anaylsis",
        url: "/",
        icon: "chart.svg",
      },
      {
        id: 2,
        title: "Doping risk Analysis",
        url: "/",
        icon: "log.svg",
      },
      {
        id: 2,
        title: "Recovery Analysis",
        url: "/",
        icon: "log.svg",
      },
      {
        id: 1,
        title: "Physical Performance Analysis",
        url: "/",
        icon: "chart.svg",
      },
    
    ],
  },
];

export const topDealUsers = [
  {
    id: 1,
    img: "https://cdn.shopify.com/s/files/1/0083/7622/files/DALL_E_2023-11-29_22.41.18_-_A_dynamic_sports_arena_focused_on_track_and_field_featuring_a_large_digital_scoreboard_displaying_a_vivid_conversion_table_with_units_like_505_km_to_480x480.png?v=1701297744",
    username: "100 Meters Sprint",
    email: "Male",
    amount: "12/08/2024",
  },
  {
    id: 2,
    img: "https://i.ytimg.com/vi/kXoBj_BIW0I/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBqB1Rj5dld-XPQwHte2drbNKceeQ",
    username: "200 Meters Sprint",
    email: "Male",
    amount: "14/08/2024",
  },
  {
    id: 3,
    img: "https://images.supersport.com/media/5yxo4ssm/so_050821_ath_mfin_400_f.png?width=1920&quality=90&format=webp",
    username: "400 Meters Sprint",
    email: "Male",
    amount: "16/08/2024",
  },
  {
    id: 4,
    img: "https://wsbt.com/resources/media2/16x9/1304/986/0x131/90/30185fb2-b6d6-4271-a064-3bfaa6721d70-Lyles.PNG",
    username: "4x100 meters Relay",
    email: "Male",
    amount: "18/08/2024",
},
{
  id: 5,
  img: "https://w7.pngwing.com/pngs/205/373/png-transparent-relay-race-athletics-long-distance-running-racing-shooting-physical-fitness-hand-human-thumbnail.png",
  username: "4x400 meters relay",
  email: "Male",
  amount: "20/08/2024",
},
{
  id: 6,
  img: "https://www.hawaiitribune-herald.com/wp-content/uploads/2024/08/web1_USrelaysWR-1.jpg",
  username: "4x400 Meters Mixed Relay",
  email: "Male",
  amount: "22/08/2024",
},
 
];

export const chartBoxUser = {
  color: "#8884d8",
  icon: "/heart.svg",
  title: "Heart Rate",
  number: "88 bpm",
  dataKey: "Rate",
  percentage: 101,
  chartData: [
    { name: "Sun",Rate: 59 },
    { name: "Mon", Rate: 60 },
    { name: "Tue", Rate: 50 },
    { name: "Wed", Rate: 82 },
    { name: "Thu", Rate: 85 },
    { name: "Fri", Rate: 101 },
    { name: "Sat", Rate: 96 },
  ],
};

export const chartBoxProduct = {
  color: "skyblue",
  icon: "/productIcon.svg",
  title: "Respiration Rate",
  number: "16 BPM",
  dataKey: "respiratoryRate",
  percentage: 2,
  chartData: [
    { name: "Sun", respiratoryRate: 14 },  // Breath rate per minute
    { name: "Mon", respiratoryRate: 15 },
    { name: "Tue", respiratoryRate: 16 },
    { name: "Wed", respiratoryRate: 17 },
    { name: "Thu", respiratoryRate: 18 },
    { name: "Fri", respiratoryRate: 17 },
    { name: "Sat", respiratoryRate: 16 },
  ],
};
export const chartBoxProduc = {
  color: "skyblue",
  icon: "/productIcon.svg",
  title: "Glucose Level",
  number: "90 mg/d",
  dataKey: "glucoseLevel",
  percentage: 2,
  chartData: [
    { name: "Sun", glucoseLevel: 85 },  // Glucose levels in mg/dL
    { name: "Mon", glucoseLevel: 88 },
    { name: "Tue", glucoseLevel: 90 },
    { name: "Wed", glucoseLevel: 92 },
    { name: "Thu", glucoseLevel: 95 },
    { name: "Fri", glucoseLevel: 93 },
    { name: "Sat", glucoseLevel: 90 },
  ],
};
export const chartBoxRevenue = {
  color: "teal",
  icon: "/sleep.svg",
  title: "Total Sleep",
  number: "7.5 hrs",
  dataKey: "sleep",
  percentage: -12,
  chartData: [
    { name: "Sun", sleep: 6.5 },
    { name: "Mon", sleep: 7.2 },
    { name: "Tue", sleep: 8.0 },
    { name: "Wed", sleep: 7.0 },
    { name: "Thu", sleep: 6.8 },
    { name: "Fri", sleep: 7.5 },
    { name: "Sat", sleep: 8.2 },
  ],
};
export const chartBoxConversion = {
  color: "gold",
  icon: "/conversionIcon.svg",
  title: "Fatigue Rate",
  number: "3.8 / 5 RPE",
  dataKey: "fatigue",
  percentage: 12,
  chartData: [
    { name: "Sun", fatigue: 3.5 },
    { name: "Mon", fatigue: 4.0 },
    { name: "Tue", fatigue: 4.2 },
    { name: "Wed", fatigue: 3.8 },
    { name: "Thu", fatigue: 3.6 },
    { name: "Fri", fatigue: 4.1 },
    { name: "Sat", fatigue: 3.9 },
  ],
};
export const chartBoxConv = {
  color: "gold",
  icon: "/conversionIcon.svg",
  title: "Muscle Oxygenation (SmO2)",
  number: "70%",
  dataKey: "SmO2",
  percentage: 12,
  chartData: [
    { name: "Sun", SmO2: 65 },  // SmO2 percentage
    { name: "Mon",SmO2: 68 },
    { name: "Tue", SmO2: 70 },
    { name: "Wed", SmO2: 72 },
    { name: "Thu", SmO2: 73 },
    { name: "Fri", SmO2: 71 },
    { name: "Sat", SmO2: 70 },
  ],
};
export const barChartBoxRevenue = {
  title: "Calories Burned (in kcal)",
  color: "#8884d8",
  dataKey: "calories",
  chartData: [
    { name: "Sun", calories: 2200 },
    { name: "Mon", calories: 2500 },
    { name: "Tue", calories: 2400 },
    { name: "Wed", calories: 2600 },
    { name: "Thu", calories: 2300 },
    { name: "Fri", calories: 2700 },
    { name: "Sat", calories: 2550 },
  ],
};

export const barChartBoxRev = {
  title: "Hydration Levels",
  color: "#8884d8",
  dataKey: "hydration",
  chartData: [
     { name: "Sun", hydration: 2.3 },
    { name: "Mon", hydration: 2.5 },
    { name: "Tue", hydration: 2.7 },
    { name: "Wed", hydration: 2.4 },
    { name: "Thu", hydration: 2.6 },
    { name: "Fri", hydration: 2.8 },
    { name: "Sat", hydration: 2.9 },
  ],
};

export const barChartBoxVisit = {
  title: "Recovery Time (Hrs)",
  color: "#FF8042",
  dataKey: "recovery",
  chartData: [
    { name: "Sun", recovery: 20 },
    { name: "Mon", recovery: 22 },
    { name: "Tue", recovery: 24 },
    { name: "Wed", recovery: 26 },
    { name: "Thu", recovery: 23 },
    { name: "Fri", recovery: 25 },
    { name: "Sat", recovery: 27 },
  ],
};


export const userRows = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    lastName: "Hubbard",
    firstName: "Eula",
    email: "kewez@@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Manning",
    firstName: "Stella",
    email: "comhuhmit@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/1587009/pexels-photo-1587009.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Greer",
    firstName: "Mary",
    email: "ujudokon@hottmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/871495/pexels-photo-871495.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Williamson",
    firstName: "Mildred",
    email: "tinhavabe@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/1758144/pexels-photo-1758144.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Gross",
    firstName: "Jose",
    email: "gobtagbes@yahoo.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/769745/pexels-photo-769745.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Sharp",
    firstName: "Jeremy",
    email: "vulca.eder@mail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Lowe",
    firstName: "Christina",
    email: "reso.bilic@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/428364/pexels-photo-428364.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Dean",
    firstName: "Garrett",
    email: "codaic@mail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 9,
    img: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Parsons",
    firstName: "Leah",
    email: "uzozor@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
  },
  {
    id: 10,
    img: "https://images.pexels.com/photos/775358/pexels-photo-775358.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Reid",
    firstName: "Elnora",
    email: "tuhkabapu@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 11,
    img: "https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Dunn",
    firstName: "Gertrude",
    email: "gibo@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
    verified: true,
  },
  {
    id: 12,
    img: "https://images.pexels.com/photos/774095/pexels-photo-774095.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Williams",
    firstName: "Mark",
    email: "tic.harvey@hotmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
  },
  {
    id: 13,
    img: "https://images.pexels.com/photos/761977/pexels-photo-761977.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Cruz",
    firstName: "Charlotte",
    email: "ceuc@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
  },
  {
    id: 14,
    img: "https://images.pexels.com/photos/927022/pexels-photo-927022.jpeg?auto=compress&cs=tinysrgb&w=1600",
    lastName: "Harper",
    firstName: "Sara",
    email: "bafuv@hotmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
  },
  {
    id: 15,
    img: "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    lastName: "Griffin",
    firstName: "Eric",
    email: "ubi@gmail.com",
    phone: "123 456 789",
    createdAt: "01.02.2023",
  },
];

export const products = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Cristiano Roger",
    color: "N/A",
    producer: "N/A",
    price: "N/A",
    createdAt: "01.02.2023",
    inStock: true,
    lastMessageTime: "01.02.2023 10:00 AM",
    messagePreview: "Looking forward to our next training session!",
    status: "Unread",
    isConfidential: true,
    reportStatus: false,
    chatType: "One-on-One",
    athleteRole: "Professional",
    securityLevel: "High",
    isActive: true,
},
{
    id: 2,
    img:  "https://images.pexels.com/photos/927022/pexels-photo-927022.jpeg?auto=compress&cs=tinysrgb&w=1600",
    name: "LeBron James",
    color: "N/A",
    producer: "N/A",
    price: "N/A",
    createdAt: "01.02.2023",
    inStock: true,
    lastMessageTime: "01.02.2023 10:15 AM",
    messagePreview: "Any updates on the nutrition plan?",
    status: "Read",
    isConfidential: true,
    reportStatus: false,
    chatType: "Group",
    athleteRole: "Olympian",
    securityLevel: "Medium",
    isActive: true,
},
{
    id: 3,
    img:  "https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg?auto=compress&cs=tinysrgb&w=1600",
    name: "Misty Copeland",
    color: "N/A",
    producer: "N/A",
    price: "N/A",
    createdAt: "01.02.2023",
    inStock: true,
    lastMessageTime: "01.02.2023 11:00 AM",
    messagePreview: "Let's discuss the training schedule for next week.",
    status: "Unread",
    isConfidential: true,
    reportStatus: false,
    chatType: "One-on-One",
    athleteRole: "Amateur",
    securityLevel: "High",
    isActive: true,
},
{
    id: 4,
    img: "https://images.pexels.com/photos/769745/pexels-photo-769745.jpeg?auto=compress&cs=tinysrgb&w=1600",
    name: "Serena Deeb",
    color: "N/A",
    producer: "N/A",
    price: "N/A",
    createdAt: "01.02.2023",
    inStock: true,
    lastMessageTime: "01.02.2023 11:30 AM",
    messagePreview: "Can we reschedule our meeting?",
    status: "Read",
    isConfidential: true,
    reportStatus: false,
    chatType: "One-on-One",
    athleteRole: "Professional",
    securityLevel: "Medium",
    isActive: true,
},
{
    id: 5,
    img: "https://images.pexels.com/photos/775358/pexels-photo-775358.jpeg?auto=compress&cs=tinysrgb&w=1600",
    name: "Lionel Reddy",
    color: "N/A",
    producer: "N/A",
    price: "N/A",
    createdAt: "01.02.2023",
    inStock: false,
    lastMessageTime: "01.02.2023 12:00 PM",
    messagePreview: "What time do we meet tomorrow?",
    status: "Unread",
    isConfidential: true,
    reportStatus: true,
    chatType: "Group",
    athleteRole: "Olympian",
    securityLevel: "High",
    isActive: true,
},
{
    id: 6,
    img: "https://images.pexels.com/photos/1758144/pexels-photo-1758144.jpeg?auto=compress&cs=tinysrgb&w=1600",
    name: "Tom Brady",
    color: "N/A",
    producer: "N/A",
    price: "N/A",
    createdAt: "01.02.2023",
    inStock: true,
    lastMessageTime: "01.02.2023 01:00 PM",
    messagePreview: "I need more time to recover.",
    status: "Read",
    isConfidential: true,
    reportStatus: false,
    chatType: "One-on-One",
    athleteRole: "Professional",
    securityLevel: "Medium",
    isActive: true,
},
{
    id: 7,
    img: "https://images.pexels.com/photos/871495/pexels-photo-871495.jpeg?auto=compress&cs=tinysrgb&w=1600",
    name: "Serena Williams",
    color: "N/A",
    producer: "N/A",
    price: "N/A",
    createdAt: "01.02.2023",
    inStock: false,
    lastMessageTime: "01.02.2023 02:00 PM",
    messagePreview: "I want to talk about my recent performance.",
    status: "Unread",
    isConfidential: true,
    reportStatus: false,
    chatType: "Group",
    athleteRole: "Amateur",
    securityLevel: "Low",
    isActive: true,
},
{
    id: 8,
    img: "https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=1600",
    name: "Simone Biles",
    color: "N/A",
    producer: "N/A",
    price: "N/A",
    createdAt: "01.02.2023",
    inStock: true,
    lastMessageTime: "01.02.2023 03:00 PM",
    messagePreview: "Can we have a follow-up on my last session?",
    status: "Read",
    isConfidential: true,
    reportStatus: false,
    chatType: "One-on-One",
    athleteRole: "Professional",
    securityLevel: "Medium",
    isActive: true,
},
{
    id: 9,
    img:"https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    name: "Michael Phelps",
    color: "N/A",
    producer: "N/A",
    price: "N/A",
    createdAt: "01.02.2023",
    inStock: true,
    lastMessageTime: "01.02.2023 04:00 PM",
    messagePreview: "I’m feeling great about my training!",
    status: "Unread",
    isConfidential: true,
    reportStatus: false,
    chatType: "Group",
    athleteRole: "Olympian",
    securityLevel: "High",
    isActive: true,
},
{
    id: 10,
    img: "https://images.pexels.com/photos/774095/pexels-photo-774095.jpeg?auto=compress&cs=tinysrgb&w=1600",
    name: "Usain Bolt",
    color: "N/A",
    producer: "N/A",
    price: "N/A",
    createdAt: "01.02.2023",
    inStock: true,
    lastMessageTime: "01.02.2023 05:00 PM",
    messagePreview: "Looking for advice on recovery techniques.",
    status: "Read",
    isConfidential: true,
    reportStatus: false,
    chatType: "One-on-One",
    athleteRole: "Amateur",
    securityLevel: "Medium",
    isActive: true,
},

];



export const singleUser = {
  id: 1,
  title: "Amlan Borgohain",
  img: "https://www.jioinstitute.edu.in/sites/default/files/styles/webp/public/article/WhatsApp%20Image%202023-06-20%20at%207.37.52%20PM.jpeg.webp?itok=a-fUcHbY",
  info: {
    username: "AmlanB21",
    fullname: "Amlan Borgohain",
    email: "AmlanBor@gmail.com",
    phone: "123 456 789",
    status: "verified"
  },
  chart: {
    dataKeys: [
      { name: "trainingSessions", color: "#82ca9d" },
      { name: "goalsAchieved", color: "#8884d8" },
    ],
    data: [
      {
        name: "Week 1",
        trainingSessions: 5,
        goalsAchieved: 3,
      },
      {
        name: "Week 2",
        trainingSessions: 6,
        goalsAchieved: 4,
      },
      {
        name: "Week 3",
        trainingSessions: 4,
        goalsAchieved: 2,
      },
      {
        name: "Week 4",
        trainingSessions: 7,
        goalsAchieved: 5,
      },
      {
        name: "Week 5",
        trainingSessions: 5,
        goalsAchieved: 3,
      },
      {
        name: "Week 6",
        trainingSessions: 8,
        goalsAchieved: 6,
      },
      {
        name: "Week 7",
        trainingSessions: 6,
        goalsAchieved: 4,
      },
    ],
  },
  
  activities: [
    {
      text: "Musculoskeletal Assessments : Pending",
      time: "Scheduled : 16 August 2024",
    },
    {
      text: "Testosterone Testing : Pending",
      time: "Scheduled : 18 August 2024",
    },
    {
      text: "Urine Testing : Completed",
      time: "1 week ago",
    },
    {
      text: "Blood test : Completed",
      time: "1 week ago",
    },
    {
      text: "Lactate Threshold Test : Completed",
      time: "1 week ago",
    },
    {
      text: "VO2 Max Test : Completed",
      time: "1 week ago",
    },
  ],
};
export const singleProduct = {
  id: 1,
  title: "Playstation 5 Digital Edition",
  img: "https://store.sony.com.au/on/demandware.static/-/Sites-sony-master-catalog/default/dw1b537bbb/images/PLAYSTATION5W/PLAYSTATION5W.png",
  info: {
    productId: "Ps5SDF1156d",
    color: "white",
    price: "$250.99",
    producer: "Sony",
    export: "Japan",
  },
  chart: {
    dataKeys: [
      { name: "visits", color: "#82ca9d" },
      { name: "orders", color: "#8884d8" },
    ],
    data: [
      {
        name: "Sun",
        visits: 4000,
        orders: 2400,
      },
      {
        name: "Mon",
        visits: 3000,
        orders: 1398,
      },
      {
        name: "Tue",
        visits: 2000,
        orders: 3800,
      },
      {
        name: "Wed",
        visits: 2780,
        orders: 3908,
      },
      {
        name: "Thu",
        visits: 1890,
        orders: 4800,
      },
      {
        name: "Fri",
        visits: 2390,
        orders: 3800,
      },
      {
        name: "Sat",
        visits: 3490,
        orders: 4300,
      },
    ],
  },
  activities: [
    {
      text: "John Doe purchased Playstation 5 Digital Edition",
      time: "3 day ago",
    },
    {
      text: "Jane Doe added Playstation 5 Digital Edition into their wishlist",
      time: "1 week ago",
    },
    {
      text: "Mike Doe purchased Playstation 5 Digital Edition",
      time: "2 weeks ago",
    },
    {
      text: "Anna Doe reviewed the product",
      time: "1 month ago",
    },
    {
      text: "Michael Doe added Playstation 5 Digital Edition into their wishlist",
      time: "1 month ago",
    },
    {
      text: "Helen Doe reviewed the product",
      time: "2 months ago",
    },
  ],
};
